### ISSUE TITLE
docgen --serve . errors with errno 10022

### ISSUE THREAD

**Issue by IssuesMigrator** [dart-lang/dartdoc-viewer#101]
_From [theburni...@gmail.com](https://code.google.com/u/110073317956783717735/) on July 05, 2014 03:08:34_

What steps will reproduce the problem? 1. clone repo https://github.com/theburningmonk/raven-dart.git 2. run "pub get" at root level of project
3. run "docgen --serve ." What is the expected output? What do you see instead? Expected to see the API doc being hosted on localhost:8080 What version of the product are you using? On what operating system? Dart SDK 1.5.1, Window 7 64 bit Please provide any additional information below. Here's the output from console:

E:\SourceCode\personal\raven-dart\raven_dart>docgen --serve .
Using default options for documenting a single package: --start-page=raven_dart
Package Root: .\packages
Added to libraries: .\lib\raven_dart.dart
Added to libraries: E:\SourceCode\personal\raven-dart\raven_dart\lib\raven_dart.
dart
Added to libraries: C:\Users\theburningmonk\AppData\Roaming\Pub\Cache\hosted\pub
.dartlang.org\collection-0.9.3+1\lib\algorithms.dart
Added to libraries: C:\Users\theburningmonk\AppData\Roaming\Pub\Cache\hosted\pub
.dartlang.org\collection-0.9.3+1\lib\collection.dart
Added to libraries: C:\Users\theburningmonk\AppData\Roaming\Pub\Cache\hosted\pub
.dartlang.org\collection-0.9.3+1\lib\equality.dart
Added to libraries: C:\Users\theburningmonk\AppData\Roaming\Pub\Cache\hosted\pub
.dartlang.org\collection-0.9.3+1\lib\iterable_zip.dart
Added to libraries: C:\Users\theburningmonk\AppData\Roaming\Pub\Cache\hosted\pub
.dartlang.org\collection-0.9.3+1\lib\priority_queue.dart
Added to libraries: C:\Users\theburningmonk\AppData\Roaming\Pub\Cache\hosted\pub
.dartlang.org\collection-0.9.3+1\lib\wrappers.dart
Added to libraries: C:\Users\theburningmonk\AppData\Roaming\Pub\Cache\hosted\pub
.dartlang.org\uuid-0.3.2\lib\uuid.dart
Added to libraries: C:\Users\theburningmonk\AppData\Roaming\Pub\Cache\hosted\pub
.dartlang.org\uuid-0.3.2\lib\uuid_client.dart
Added to libraries: C:\Users\theburningmonk\AppData\Roaming\Pub\Cache\hosted\pub
.dartlang.org\uuid-0.3.2\lib\uuid_server.dart
Added to libraries: C:\Users\theburningmonk\AppData\Roaming\Pub\Cache\hosted\pub
.dartlang.org\crypto-0.9.0\lib\crypto.dart
Added to libraries: C:\Users\theburningmonk\AppData\Roaming\Pub\Cache\hosted\pub
.dartlang.org\matcher-0.10.1+1\lib\matcher.dart
Added to libraries: C:\Users\theburningmonk\AppData\Roaming\Pub\Cache\hosted\pub
.dartlang.org\matcher-0.10.1+1\lib\mirror_matchers.dart
Added to libraries: C:\Users\theburningmonk\AppData\Roaming\Pub\Cache\hosted\pub
.dartlang.org\http-0.11.1+1\lib\browser_client.dart
Added to libraries: C:\Users\theburningmonk\AppData\Roaming\Pub\Cache\hosted\pub
.dartlang.org\http-0.11.1+1\lib\http.dart
Added to libraries: C:\Users\theburningmonk\AppData\Roaming\Pub\Cache\hosted\pub
.dartlang.org\http-0.11.1+1\lib\testing.dart
Added to libraries: C:\Users\theburningmonk\AppData\Roaming\Pub\Cache\hosted\pub
.dartlang.org\bignum-0.0.5\lib\bignum.dart
Added to libraries: C:\Users\theburningmonk\AppData\Roaming\Pub\Cache\hosted\pub
.dartlang.org\cipher-0.7.1\lib\api.dart
Added to libraries: C:\Users\theburningmonk\AppData\Roaming\Pub\Cache\hosted\pub
.dartlang.org\cipher-0.7.1\lib\cipher.dart
Added to libraries: C:\Users\theburningmonk\AppData\Roaming\Pub\Cache\hosted\pub
.dartlang.org\stack_trace-1.0.2\lib\stack_trace.dart
Added to libraries: C:\Users\theburningmonk\AppData\Roaming\Pub\Cache\hosted\pub
.dartlang.org\fixnum-0.9.0\lib\fixnum.dart
Added to libraries: C:\Users\theburningmonk\AppData\Roaming\Pub\Cache\hosted\pub
.dartlang.org\path-1.2.1\lib\path.dart
Added to libraries: C:\Users\theburningmonk\AppData\Roaming\Pub\Cache\hosted\pub
.dartlang.org\http_parser-0.0.2+3\lib\http_parser.dart
Added to libraries: C:\Users\theburningmonk\AppData\Roaming\Pub\Cache\hosted\pub
.dartlang.org\string_scanner-0.0.3\lib\string_scanner.dart
Added to libraries: C:\Users\theburningmonk\AppData\Roaming\Pub\Cache\hosted\pub
.dartlang.org\unittest-0.11.0+2\lib\compact_vm_config.dart
Added to libraries: C:\Users\theburningmonk\AppData\Roaming\Pub\Cache\hosted\pub
.dartlang.org\unittest-0.11.0+2\lib\html_config.dart
Added to libraries: C:\Users\theburningmonk\AppData\Roaming\Pub\Cache\hosted\pub
.dartlang.org\unittest-0.11.0+2\lib\html_enhanced_config.dart
Added to libraries: C:\Users\theburningmonk\AppData\Roaming\Pub\Cache\hosted\pub
.dartlang.org\unittest-0.11.0+2\lib\html_individual_config.dart
Added to libraries: C:\Users\theburningmonk\AppData\Roaming\Pub\Cache\hosted\pub
.dartlang.org\unittest-0.11.0+2\lib\unittest.dart
Added to libraries: C:\Users\theburningmonk\AppData\Roaming\Pub\Cache\hosted\pub
.dartlang.org\unittest-0.11.0+2\lib\vm_config.dart
Added to libraries: C:\Users\theburningmonk\AppData\Roaming\Pub\Cache\hosted\pub
.dartlang.org\source_maps-0.9.2+3\lib\builder.dart
Added to libraries: C:\Users\theburningmonk\AppData\Roaming\Pub\Cache\hosted\pub
.dartlang.org\source_maps-0.9.2+3\lib\parser.dart
Added to libraries: C:\Users\theburningmonk\AppData\Roaming\Pub\Cache\hosted\pub
.dartlang.org\source_maps-0.9.2+3\lib\printer.dart
Added to libraries: C:\Users\theburningmonk\AppData\Roaming\Pub\Cache\hosted\pub
.dartlang.org\source_maps-0.9.2+3\lib\refactor.dart
Added to libraries: C:\Users\theburningmonk\AppData\Roaming\Pub\Cache\hosted\pub
.dartlang.org\source_maps-0.9.2+3\lib\source_maps.dart
Added to libraries: C:\Users\theburningmonk\AppData\Roaming\Pub\Cache\hosted\pub
.dartlang.org\source_maps-0.9.2+3\lib\span.dart
Add to SDK: dart:async
Add to SDK: dart:collection
Add to SDK: dart:convert
Add to SDK: dart:core
Add to SDK: dart:html
Add to SDK: dart:indexed_db
Add to SDK: dart:io
Add to SDK: dart:isolate
Add to SDK: dart:js
Add to SDK: dart:math
Add to SDK: dart:mirrors
Add to SDK: dart:profiler
Add to SDK: dart:typed_data
Add to SDK: dart:svg
Add to SDK: dart:web_audio
Add to SDK: dart:web_gl
Add to SDK: dart:web_sql
SDK Root: E:\dart\dart-sdk
Cannot find MDN docs expected at E:\dart\utils/apidoc/mdn/database.json
process output: Resolving dependencies... (2.7s)
> analyzer 0.15.7 (was 0.13.6) (6 newer versions available)
> args 0.11.0+1 (was 0.10.0+2)
  barback 0.13.0 (8 newer versions available)
  browser 0.10.0+2
> code_transformers 0.1.4+2 (was 0.1.3+1)
> collection 0.9.4 (was 0.9.2)
  csslib 0.10.0+1
  html5lib 0.11.0+1
  logging 0.9.1+1
> matcher 0.10.1+1 (was 0.10.0)
> observe 0.10.1+2 (was 0.10.0)
> path 1.2.1 (was 1.2.0)
> polymer 0.10.1+2 (was 0.10.0) (6 newer versions available)
  polymer_expressions 0.10.0 (3 newer versions available)
> smoke 0.1.0+1 (was 0.1.0)
> source_maps 0.9.2+3 (was 0.9.1)
  stack_trace 0.9.3+2 (3 newer versions available)
  template_binding 0.10.0 (1 newer version available)
> unittest 0.11.0+2 (was 0.11.0)
  utf 0.9.0
  web_components 0.3.4 (3 newer versions available)
  yaml 0.9.0+2 (4 newer versions available)
Changed 11 dependencies!

process stderr:
Compiling the app to JavaScript.
process output: Done! All files written to "out"
Running dart2js

Done

process s...

_Original issue: http://code.google.com/p/dart/issues/detail?id=19842_

**Comment by sethladd** [comment]
Thanks for the report. Future work is happening here: https://github.com/dart-lang/dartdoc
