### ISSUE TITLE
dart:math max function is not discoverable in the docs

### ISSUE THREAD

**Issue by IssuesMigrator** [dart-lang/dartdoc-viewer#102]
_From [ccala...@google.com](https://code.google.com/u/117916205690095755990/) on July 11, 2014 21:09:30_

go to https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart-math#id_max you will see the max function.  yay.
in the "search api" box in the upper right, type "max".
you will see 10 suggestions - there is no scroll bar.
the max function in dart:math is most likely the max you want but it's not in the list.
now, without choosing any of those other max functions, hit enter.
it will take you to some dart:html thingy.  not the max i want!

so the problems are
(1) suggest should have a smarter ranking.  dart:math's max is more popular than dart:html's.
(2) there needs to be some way of discovering every max function, popular or not,
like the wikipedia disambiguation pages.

_Original issue: http://code.google.com/p/dart/issues/detail?id=20000_

**Comment by sethladd** [comment]
Moved over to https://github.com/dart-lang/dartdoc/issues/7
