### ISSUE TITLE
Have a way to refer to the package docs from within code, and to code entities from the README.md

### ISSUE THREAD

**Issue by IssuesMigrator** [dart-lang/dartdoc-viewer#105]
_From @alan-knight on July 19, 2014 01:13:03_

Right now there's no way to refer to the package docs (i.e. the contents of the README) without using the full URL. And on dartdocs.org that means including the version number.

Similarly, references to entities in the package aren't resolved from the README.md. There's not really a scope, but we might reasonably assume that the scope is the main library, if there is one.

_Original issue: http://code.google.com/p/dart/issues/detail?id=20112_

**Comment by sethladd** [comment]
This sounds like an issue with dartdocs.org's URL space. Is there anything the new dartdoc tool should do?
