### ISSUE TITLE
Dart docs viewer input box moves the cursor to the end for every keypress

### ISSUE THREAD

**Issue by IssuesMigrator** [dart-lang/dartdoc-viewer#109]
_From [gy...@google.com](https://code.google.com/u/115613504859293134805/) on August 05, 2014 16:36:00_

What steps will reproduce the problem? 1. Go to: https://docs.angulardart.org/ 2. On the search box in the top right corner type "foobar"
3. Go back to insert 'lish' after foo, so it reads "foolishbar" What is the expected output? What do you see instead? When I press the 'l' it immediately jumps to the end of the input test.
I expect to be able to type 'lish' without the cursor jumping. What version of the product are you using? Publicly available website https://docs.angulardart.org/ On what operating system? Tested on OSX and Linux. What browser (if applicable)? Tested in 
Linux / Chrome 36.0.1985.125
OSX / Chrome 38.0.2096.0 dev

_Original issue: http://code.google.com/p/dart/issues/detail?id=20367_

**Comment by sethladd** [comment]
Thanks for the report. Just tried this on api.dartlang.org and it looks like the cursor is no longer moving while the user is editing and typing in the middle of the search box.
