### ISSUE TITLE
Adding user analytic settings to dartdoc-viewer 

### ISSUE THREAD

**Issue by IssuesMigrator** [dart-lang/dartdoc-viewer#111]
_From [financeC...@gmail.com](https://code.google.com/u/104569492481999771226/) on August 10, 2014 20:59:07_

Explain how a user can take advantage of analytics settings for docgen/dartdoc-viewer. https://code.google.com/p/dart/issues/detail?id=19372

_Original issue: http://code.google.com/p/dart/issues/detail?id=20451_

**Comment by sethladd** [comment]
Now tracked at https://github.com/dart-lang/dartdoc/issues/56
