### ISSUE TITLE
External links to anchors don't always scroll to the anchor

### ISSUE THREAD

**Issue by IssuesMigrator** [dart-lang/dartdoc-viewer#113]
_From @kwalrath on August 30, 2014 00:10:40_

When I go to http://www.dartdocs.org/documentation/angular/0.14.0/index.html#angular/angular-tracing@id_traceDetectWTF (for example), traceDetectWTF is neither highlighted nor scrolled to. (This is in Chrome 38.) If I click traceDetectWTF in the TOC to the right, then the page correctly scrolls to and highlights that anchor, without the URL changing.

However, if I go to https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart-core.DateTime#id_isBefore , it *does* go to the right place.

Perhaps dartdocs.org uses a different version of DartDocViewer? And/or maybe it's the difference in URL formats that matters? More details at https://github.com/dart-lang/www.dartlang.org/pull/362 .

_Original issue: http://code.google.com/p/dart/issues/detail?id=20752_

**Comment by sethladd** [comment]
Future work is happening here: https://github.com/dart-lang/dartdoc

We are preferring static docs and thus we expect anchors and IDs to scroll you to the correct location.
