### ISSUE TITLE
dartdoc viewer issues with SDK version number

### ISSUE THREAD

**Issue by IssuesMigrator** [dart-lang/dartdoc-viewer#114]
_From @alan-knight on September 08, 2014 18:58:40_

Right now for the stable channel I'm not seeing an SDK version number at all. For dev and bleeding edge I'm seeing 1.7.0. It's possible there's a change that just needs to percolate into stable, but there may also be a problem. And for bleeding edge and dev it would probably be useful to show the version in a way that identifies the dev version or the bleeding edge build number rather than just saying it's 1.7.0.

_Original issue: http://code.google.com/p/dart/issues/detail?id=20848_

**Comment by sethladd** [comment]
Now tracked at https://github.com/dart-lang/dartdoc/issues/66
