### ISSUE TITLE
Middle-clicking on links do not open them in a new tab.

### ISSUE THREAD

**Issue by IssuesMigrator** [dart-lang/dartdoc-viewer#115]
_From @lrhn on September 09, 2014 09:41:44_

In Chrome/Linux, when I middle-click (click using the mouse's middle button/scroll wheel) on a link, the new page loads in the same tab instead of in another tab. 
This breaks normal browsing, where middle-click is used to open links in new tabs. It is a serious usability problem.
Middle-clicking works fine on other sites, this is a DartDoc problem only.

_Original issue: http://code.google.com/p/dart/issues/detail?id=20860_

**Comment by sethladd** [comment]
Future work is happening at https://github.com/dart-lang/dartdoc

We are preferring static docs, and thus we expect links and tabs to operate correctly.
