### ISSUE TITLE
misaligned footer

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/dartdoc-viewer#125]
The footer:
```
with SDK Version 1.10.0
Dart API Documentation
```

appears at the end of the text of the main area, but it's currently aligned with the left-hand navigation bar. If the text in the main area is small, the text appears half-visible behind the navigation bar. See attached image for an example.

![viewer-bug](https://cloud.githubusercontent.com/assets/2049220/7028621/d84941be-dd0b-11e4-8a72-56e6f01142d5.png)

**Comment by sethladd** [comment]
Thanks for the report. Since this doesn't look critical, I'm going to close. Look for the new dartdoc, coming soon!
