### ISSUE TITLE
[Feature] Implement a scroll spy in the navigator

### ISSUE THREAD

**Issue by vicb** [dart-lang/dartdoc-viewer#14]
It would be great to highlight the current section in the navigator (right bar). This is something I have implement in dart-lang/dartlang.org#292. It can implement this in the API viewer if there is some interest.

**Comment by sethladd** [comment]
I noticed that both the right and left bars are not highlighted. Agreed, we should do this.

**Comment by sethladd** [comment]
This issue was moved to dart-lang/dartdoc#115
