### ISSUE TITLE
[Feature] History via tabs

### ISSUE THREAD

**Issue by vicb** [dart-lang/dartdoc-viewer#15]
I really enjoy browsing the [ExtJS API doc](http://docs.sencha.com/extjs/4.0.7/#!/api). It features a tab navigation at the top that shows the history of the docs you've consulted.

May be it's only me and my deficient memory but I think it's really helpful. 

I could work on this feature if there is some interest ?

**Comment by sethladd** [comment]
Thanks for the suggestion. New work is happening here: https://github.com/dart-lang/dartdoc

There are no plans to add a tabbed doc UI, but the new system is being designed to make it easier to generate different UIs.
