### ISSUE TITLE
If documentation for a dart: library does not exist link to api.dartlang.org

### ISSUE THREAD

**Issue by caffinatedmonkey** [dart-lang/dartdoc-viewer#21]
If the documentation for a `dart:*` library does not exist link back to the api.dartlang.org version.

<sub>This feature needs to be applied to the dartdoc-viewer, this repository.</sub>

**Comment by sethladd** [comment]
Thanks for the report! If I go to https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:foo (which is not a valid link) then I am redirected to the home of api.dartlang.org.

**Comment by caffinatedmonkey** [comment]
No, I meant in generated, self hosted documentation. If the documentation for the core library is skipped, it should link back to api.dartlang.org. I haven't checked this project out in a few months so please excuse me if I am missing something.
