### ISSUE TITLE
Improve page titles

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/dartdoc-viewer#24]
I'm very happy that we now have dynamic page titles, but I think we can improve them. (I originally wrote this as a comment on #22, so you might experience deja vu.)

The title (of https://api.dartlang.org/apidocs/channels/stable/#dart-core.Expando, for example) is a little odd:
dart-core.Expando API Docs

I'd like something like this:
**Expando (dart:core) API Reference**

The most important info is on the left (where it's more likely to be visible in the tab), and there's a : instead of a - after "dart".

Here's an example of a more deeply nested API: https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/html5lib/dom_parsing.CodeMarkupVisitor

The title is now:
html5lib/dom_parsing.CodeMarkupVisitor API Docs

It might be more helpful as:
**CodeMarkupVisitor (html5lib/dom_parsing) API Reference**

(I'm not sure about `/` vs `.` as a separator. Also, "Reference" is a little more informative than "Docs", but perhaps not worth the extra characters.)

**Comment by sethladd** [comment]
This issue was moved to dart-lang/dartdoc#116
