### ISSUE TITLE
page titles in search results are not very readble

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dartdoc-viewer#33]
Steps to reproduce:

1. Open https://www.google.com/search?q=setinnerhtml+dart
2. Notice the first result is "dart-dom-html.Element.setInnerHtml API Docs"
3. Contrast with https://www.google.com/search?q=innerhtml+mdn

The most confusing part there is definitely dart-dom-html which has no meaning to a user and makes it harder to spot the Element.setInnerHtml part...

**Comment by sethladd** [comment]
This issue was moved to dart-lang/dartdoc#118
