### ISSUE TITLE
dartdoc: generic paramaters of typedefs are not displayed

### ISSUE THREAD

**Issue by IssuesMigrator** [dart-lang/dartdoc-viewer#35]
_From [kev...@j832.com](https://code.google.com/u/110066012384188006594/) on July 25, 2012 06:14:47_

See http://kevmoo.github.com/dartlib/dartlib/Func2.html This is defined as:

    typedef TR Func2<T1, T2, TR>(T1 param1, T2 param2);

_Original issue: http://code.google.com/p/dart/issues/detail?id=4196_

**Comment by sethladd** [comment]
Moved to https://github.com/dart-lang/dartdoc/issues/123
