### ISSUE TITLE
apidoc: Let search preferentially find things on the current page

### ISSUE THREAD

**Issue by IssuesMigrator** [dart-lang/dartdoc-viewer#38]
_From @jmesserly on August 31, 2012 01:10:38_

I was on http://api.dartlang.org/docs/continuous/dart_html/Element.html and I tried to search for "id". But none of the results were what I wanted. I figured out how to get there with "Element.id" but I think "search as you type" should consider the fact that I'm already on Element.html and use that to sort matches. In other words, prefer members on Element, then search more broadly.

(I'm also a bit surprised the exact text match didn't help. All of the matches were for types like IDBAny, IDBKey, etc)

_Original issue: http://code.google.com/p/dart/issues/detail?id=4853_

**Comment by sethladd** [comment]
See https://github.com/dart-lang/dartdoc/issues/7
