### ISSUE TITLE
DartDoc does not produce pleasing output for long method signatures

### ISSUE THREAD

**Issue by IssuesMigrator** [dart-lang/dartdoc-viewer#40]
_From @alan-knight on October 03, 2012 01:19:49_

If you have a method with many parameters, the DartDoc output does not look very good. For example, look at pkg/intl/lib/date_symbols.dart, which has a constructor with 24 parameters.

_Original issue: http://code.google.com/p/dart/issues/detail?id=5614_

**Comment by sethladd** [comment]
Moved to https://github.com/dart-lang/dartdoc/issues/122
