### ISSUE TITLE
apidoc: make the search box the first tab-able item

### ISSUE THREAD

**Issue by IssuesMigrator** [dart-lang/dartdoc-viewer#43]
_From [googlegr...@kaioa.com](https://code.google.com/u/113382000693943613174/) on September 08, 2013 19:00:46_

Right now, if you press tab right after loading the page, the first link of the breadcrumb navigation will be focused.

However, it would be more useful if the search field would be the first one to receive the focus. Then you could just press tab, enter your search term, use the cursor key to navigate to the desired item, and press return.

Fortunately, this is very easy to do. Since the search field's form (`.header #search-box`) is already floated to the right, it only needs to be moved up a bit in the markup. If `#search-box` is the first child of `.header`, the text field inside it will be the first focusable item.

The CSS doesn't need to be changed.

_Original issue: http://code.google.com/p/dart/issues/detail?id=13170_

**Comment by sethladd** [comment]
Thanks for the suggestion! Future work is happening here: https://github.com/dart-lang/dartdoc

See also https://github.com/dart-lang/dartdoc/issues/7
