### ISSUE TITLE
URLs in api.dartlang.org that used to work don't any more

### ISSUE THREAD

**Issue by IssuesMigrator** [dart-lang/dartdoc-viewer#44]
_From @kasperl on September 23, 2013 15:51:08_

https://www.dartlang.org/support/faq.html Q. Does Dart support JSON?#
Yes. See the JSON class in the standard library.

_Original issue: http://code.google.com/p/dart/issues/detail?id=13502_

**Comment by sethladd** [comment]
I believe we have redirects in place for the old URIs that we're aware of.
