### ISSUE TITLE
Dart docs are missing a prominent "Feedback on this document" link

### ISSUE THREAD

**Issue by IssuesMigrator** [dart-lang/dartdoc-viewer#46]
_From [mckoss@gmail.com](https://code.google.com/u/mckoss@gmail.com/) on December 19, 2013 00:28:28_

When I browse the Dart docs, and see a mistake or get confused, it's not obvious where to report those problems.

Expect:

Like other Google developer documentation (like https://developers.google.com/compute/ ) - they have a prominent "Feedback on this document" link at the top of the page to report problems or confusions.

If doc bugs are going to this issue tracker, then a link to create a new issue would be sufficient.

_Original issue: http://code.google.com/p/dart/issues/detail?id=15716_

**Comment by sethladd** [comment]
Is now https://github.com/dart-lang/dartdoc/issues/74
