### ISSUE TITLE
Optimize dartdoc-viewer to show more information with smaller screen sizes

### ISSUE THREAD

**Issue by IssuesMigrator** [dart-lang/dartdoc-viewer#48]
_From @alan-knight on January 27, 2014 21:35:20_

Some user suggestions, on the general theme of making more information visible at once, particularly on laptop or mobile screens.

However, I would have some suggestions:
- The left panel should extend from top to bottom, no need for vertical margins.
- The center panel has too much vertical and horizontal margins, especially around headers but not only. I can see only very little info on my 15' laptop on a single screen.
- The same for the right panel, too much h margins between items,
- The search auto-complete behavior layout is also very tall, does "library" need to be repeated everywhere ? Maybe icons would be better for class / property / function rather than text. With those changes, it would be great to fit the item on max 2 line. "endsWith" , "Method in String" could be replaced by "[Method Icon] String.endsWith()" with an optional emphasis on the searched item.

_Original issue: http://code.google.com/p/dart/issues/detail?id=16341_

**Comment by sethladd** [comment]
We definitely intent to optimize for smaller screens (mobile), but also narrow widths on desktop. We believe that narrow width on different devices requires different designs.

Future work is happening here: https://github.com/dart-lang/dartdoc
