### ISSUE TITLE
Progress indicator suggestion

### ISSUE THREAD

**Issue by IssuesMigrator** [dart-lang/dartdoc-viewer#50]
_From @stevemessick on February 07, 2014 08:05:04_

[user feedback] dartdocnext: Improve the progress indicator

I like the new Dart Docs (could be faster, but I think you will solve that over time), BUT the loading indicator looks like it was added because one is needed. It doesn't even match the style of the application.

My suggestion: I think the red progress bar at the top that YouTube uses would be nice for the DartDocs. To match the style of the DartDocs, the progress bar should be blue. This would be much better than a simple GIF in the middle of the text.

It should be easy to implement, there is even a project on GitHubb doing exactly that: http://github.hubspot.com/pace/docs/welcome/ (see the "flash" theme withut the spinner)
////////////////////////////////////////////////////////////////////////////////////
Editor: 1.2.0.dev_02_04 (2014-01-31)
OS: Windows 8 - amd64 (6.2)
JVM: 1.7.0_21
# projects: 1
# open dart files: 6
auto-run pub: true
localhost resolves to: 127.0.0.1
mem max/total/free: 1778 / 794 / 630 MB
thread count: 19
index: 564727 relationships in 109592 keys in 7992 sources

SDK installed: true
Dartium installed: true

_Original issue: http://code.google.com/p/dart/issues/detail?id=16619_

**Comment by sethladd** [comment]
I don't think we have a loading indicator any more.

**Comment by alan-knight** [comment]
We do, it's just gotten so lightning fast that you see it a lot less.

**Comment by sethladd** [comment]
Even better! :)
