### ISSUE TITLE
Remember user preferences for options

### ISSUE THREAD

**Issue by IssuesMigrator** [dart-lang/dartdoc-viewer#51]
_From @alan-knight on February 12, 2014 18:41:51_

We should consider using a cookie or other mechanism and remembering the user's normal preferences for settings like showing inherited members.

_Original issue: http://code.google.com/p/dart/issues/detail?id=16764_

**Comment by sethladd** [comment]
Future work is happening here: https://github.com/dart-lang/dartdoc

If the new system has preferences, agreed that we should look at storing them locally (local storage?)
