### ISSUE TITLE
If the text for something is short the build number isn't visible, obscured by the library list

### ISSUE THREAD

**Issue by IssuesMigrator** [dart-lang/dartdoc-viewer#53]
_From @alan-knight on February 13, 2014 18:27:13_

If something, e.g. a class, has a very short list of items, and we aren't showing those inherited from Object, then the build number, which is just shown at the bottom of the text along the left hand side, gets hidden underneath the library list.

_Original issue: http://code.google.com/p/dart/issues/detail?id=16803_

**Comment by sethladd** [comment]
Future work is happening in https://github.com/dart-lang/dartdoc
