### ISSUE TITLE
DartDoc suggestions not giving best match first.

### ISSUE THREAD

**Issue by IssuesMigrator** [dart-lang/dartdoc-viewer#56]
_From @lrhn on February 24, 2014 11:18:11_

If I write "reflect" in the dartdoc search box, it suggests "reflectee" as the first suggestion, and the "reflect" method is at the fifth position.
The perfect match should probably be the first one

_Original issue: http://code.google.com/p/dart/issues/detail?id=17063_

**Comment by sethladd** [comment]
Moved to https://github.com/dart-lang/dartdoc/issues/7
