### ISSUE TITLE
cleaner urls for dartdoc?

### ISSUE THREAD

**Issue by IssuesMigrator** [dart-lang/dartdoc-viewer#60]
_From @jmesserly on March 10, 2014 20:29:12_

right now linking to bleeding edge Element.enteredView looks like: https://api.dartlang.org/apidocs/channels/be/#dart-dom-html.Element@id_enteredView Seems like we could clean that up. "apidocs" and "channels" are redundant.  "edge" would make more sense than "be". #dart-dom-html.Element@id_enteredView uses a mix of dash, at-sign, and underscore to convey information.

Maybe more like: https://api.dartlang.org/edge/dart.dom.html/Element#enteredView ?

_Original issue: http://code.google.com/p/dart/issues/detail?id=17386_

**Comment by sethladd** [comment]
Moved to https://github.com/dart-lang/dartdoc/issues/119
