### ISSUE TITLE
dartdoc-viewer: clicking on class section headers (Constructors, Properties, Methods, etc) does nothing

### ISSUE THREAD

**Issue by IssuesMigrator** [dart-lang/dartdoc-viewer#62]
_From @kevmoo on March 12, 2014 01:01:10_

See https://api.dartlang.org/apidocs/channels/stable/#dart-io.Datagram Click on 'Properties' or 'Constructors'

1) Overloading @ is probably bad in the case where there are conflicts
2) Clicking does a bunch of churn that ends up with a no-op navigation

_Original issue: http://code.google.com/p/dart/issues/detail?id=17418_

**Comment by sethladd** [comment]
Future work is happening here: https://github.com/dart-lang/dartdoc

Agreed, nav menus should take the user to the location in the page.
