### ISSUE TITLE
Search for abstract class 'Application on docs.angulardart.org returns multiple entries

### ISSUE THREAD

**Issue by IssuesMigrator** [dart-lang/dartdoc-viewer#66]
_From [nao...@google.com](https://code.google.com/u/104854750843144727003/) on April 01, 2014 23:20:19_

I'm not sure what's happening here. If you go to docs.angulardart.org and search for the abstract class "Application", you find both the definition of that class (in library angular:app) as well as the usage of that class as part of the angular:app:dynamic library and the angular:app:static library.

This is confusing -- we think it should only show up at the point where it's defined, not where it's also used.

_Original issue: http://code.google.com/p/dart/issues/detail?id=17949_

**Comment by sethladd** [comment]
Moved to https://github.com/dart-lang/dartdoc/issues/7
