### ISSUE TITLE
Provide a mechanism for opening dartdoc links in a new window

### ISSUE THREAD

**Issue by IssuesMigrator** [dart-lang/dartdoc-viewer#68]
_From [nao...@google.com](https://code.google.com/u/104854750843144727003/) on April 03, 2014 00:25:06_

In our package documentation, we'd like to provide a link back to the dart:mirrors docs on dartlang.org. It would be ideal if we could do that in a new window so that the viewer could keep the angulardart docs open at the same time.

There's no way to do this in md other than explicit HTML. Could something like this (or syntax for links specific to the Dart API docs on dartlang.org) be added as a feature?

Low priority but very nice to have.

_Original issue: http://code.google.com/p/dart/issues/detail?id=17993_

**Comment by sethladd** [comment]
This issue was moved to dart-lang/dartdoc#120
