### ISSUE TITLE
dartdoc: various code links not working

### ISSUE THREAD

**Issue by IssuesMigrator** [dart-lang/dartdoc-viewer#72]
_From @jmesserly on April 09, 2014 00:26:33_

see here for examples: https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/html5lib/parser#id_parse [List<int>] -> resolves to dart-core<dart-core>
[HtmlTokenizer] -> resolves to unlinked html5lib/tokenizer.HtmlTokenizer
[Span] -> resolves to unlinked html5lib/source_maps-span.Spans

_Original issue: http://code.google.com/p/dart/issues/detail?id=18106_

**Comment by sethladd** [comment]
Moved to https://github.com/dart-lang/dartdoc/issues/124
