### ISSUE TITLE
DartDocViewer options configurations 

### ISSUE THREAD

**Issue by IssuesMigrator** [dart-lang/dartdoc-viewer#80]
_From [financeC...@gmail.com](https://code.google.com/u/104569492481999771226/) on April 21, 2014 00:41:32_

dartgen should support changing the default options. For instance I would like to have the viewer default to show all Libraries, Minimap, Inherited, Object Members and Packages.

_Original issue: http://code.google.com/p/dart/issues/detail?id=18332_

**Comment by sethladd** [comment]
Not planned for dartdoc-viewer. Future work is happening at https://github.com/dart-lang/dartdoc
