### ISSUE TITLE
api.dartlang.org main page shows full comments for things in pkg, not just first paragraph

### ISSUE THREAD

**Issue by IssuesMigrator** [dart-lang/dartdoc-viewer#81]
_From @alan-knight on April 21, 2014 19:22:06_

Go to api.dartlang.org and turn on "show packages". The page gets extremely long, and seems to be showing the full doc comment for the packages. Not sure if that's coming from docgen or the viewer.

_Original issue: http://code.google.com/p/dart/issues/detail?id=18338_

**Comment by sethladd** [comment]
We no longer show packages in api.dartlang.org
