### ISSUE TITLE
dartdoc search for members, e.g. Node.remove

### ISSUE THREAD

**Issue by IssuesMigrator** [dart-lang/dartdoc-viewer#83]
_From @jmesserly on April 24, 2014 23:24:09_

if I type something like "Node.remove" in the search box, it would be nice if dart:html Node.remove was the first result. The old doc viewer supported this, and I thought DartDocViewer did too, so not sure if this is a regression or a feature request. Either way, it would be super helpful :)

(note: I was actually searching for another property, but it was affected by the docgen bug that causes dart:html things to link to a non-existent page in Polymer, so I reproduced it using Node.remove which has a working link: https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart-dom-html.Node#id_remove )

_Original issue: http://code.google.com/p/dart/issues/detail?id=18433_

**Comment by sethladd** [comment]
Moved over to https://github.com/dart-lang/dartdoc/issues/7
