### ISSUE TITLE
provide more readable styling for annotations

### ISSUE THREAD

**Issue by IssuesMigrator** [dart-lang/dartdoc-viewer#87]
_From [nao...@google.com](https://code.google.com/u/104854750843144727003/) on May 17, 2014 00:45:32_

The annotations added by https://code.google.com/p/dart/issues/detail?id=17982 are placed at the top of the page and hard to read.

For example, in https://docs.angulardart.org/#angular-directive.NgIf , the text appears:
Decorator(children:Directive.TRANSCLUDE_CHILDREN, selector:'[ng-if]', map:const{'.':'=>condition', })
(see attached screenshot)

Can we make three changes to how this is shown in dartdoc?

1) retain line breaks present in the code instead of running everything together on one line.
2) create a section in the doc page under its own heading "Annotations" immediately following the doc body (similar to #Constructors) and place this content there, instead of at the top of the page
3) apply a style that can be referenced in css to make this monospace and/or just create it in <pre> tags

**Attachment:** [Screen Shot 2014-05-16 at 3.41.57 PM.png](http://code.google.com/p/dart/issues/detail?id=18868)

_Original issue: http://code.google.com/p/dart/issues/detail?id=18868_

**Comment by sethladd** [comment]
Moved over to https://github.com/dart-lang/dartdoc/issues/126
