### ISSUE TITLE
dartdoc-viewer renders MarkDown differently than pub.dartlang.org or GitHub

### ISSUE THREAD

**Issue by IssuesMigrator** [dart-lang/dartdoc-viewer#88]
_From [gzoe...@gmail.com](https://code.google.com/u/113356021635684004023/) on May 19, 2014 09:49:11_

What steps will reproduce the problem? 1. http://localhost:3030/core_elements_gh/dartdoc/index.html

- a link with text 'polymer_ui_elements' is rendered 'polymeruielements' with 'ui' as italic (at the top of the page linked above)
tables are not rendered (at the bottom of the page linked above) 2. 3. What is the expected output? What do you see instead? https://github.com/bwu-dart/core_elements http://pub.dartlang.org/packages/core_elements show the same README.md content

(... almost the same, pub.dartlang.org contains a commented out  text just before the table but the text is shown anyway. I already removed this text on GitHub and DartDoc but I had the explained rendering issues before and after this change).

While GitHub and pub.dartlang.org render the table differently, both render it as table while dartdoc-viewer doesn't. What version of the product are you using? On what operating system? Dart VM version: 1.4.0-dev.6.7 (Thu May 15 06:01:04 2014) on "linux_x64" Please provide any additional information below.

_Original issue: http://code.google.com/p/dart/issues/detail?id=18873_

**Comment by sethladd** [comment]
I think I understand the issue, but I can't find a repro case. Please paste a screenshot and we'll try to fix it for https://github.com/dart-lang/dartdoc
