### ISSUE TITLE
Dart APIDocs Back Button is broken.

### ISSUE THREAD

**Issue by IssuesMigrator** [dart-lang/dartdoc-viewer#90]
_From [jrr9...@gmail.com](https://code.google.com/u/115262904355300685333/) on May 30, 2014 19:31:20_

If I enter an invalid URL on the Dart API docs page it will redirect to the closest valid page, but will still push the incorrect history state into my browser, breaking my ability to use the back button. Given that the structure of the docs appears to have changed recently and Google has cached the old results, this is a frequent and somewhat annoying problem.

For instance if I Google "dart logging", this is the first result:

api.dartlang.org/logging.html

It then routes me to https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/home I am then unable to navigate back to my search results by the back button.Not a huge issue, but irritating enough to be worth mentioning, so maybe worth fixing.

Cheers.

Jacob Read

_Original issue: http://code.google.com/p/dart/issues/detail?id=19104_

**Comment by sethladd** [comment]
Future work is happening in https://github.com/dart-lang/dartdoc

The new system prefers static docs and we expect the back button to get you where you want to go.
