### ISSUE TITLE
Clicking on sidebar to member defined in a subclass navigates to the subclass, not the docs on the current class

### ISSUE THREAD

**Issue by IssuesMigrator** [dart-lang/dartdoc-viewer#91]
_From @kevmoo on June 02, 2014 22:38:46_

Example: pkg/http -> Request extends BaseRequest

Open docs for Request https://api.dartlang.org/apidocs/channels/be/dartdoc-viewer/http/http.Request Click on 'url' Property on right sidebar

Expected: page scroll to `final Uri url` on that page

Actual: navigates to BaseRequest page https://api.dartlang.org/apidocs/channels/be/dartdoc-viewer/http/http.BaseRequest#id_url

_Original issue: http://code.google.com/p/dart/issues/detail?id=19139_

**Comment by sethladd** [comment]
Confirmed. That is weird.

Future work is happening at https://github.com/dart-lang/dartdoc and we expect to address issues like this.
