### ISSUE TITLE
DartDoc has incorrect signature for function parameters.

### ISSUE THREAD

**Issue by IssuesMigrator** [dart-lang/dartdoc-viewer#94]
_From @lrhn on June 06, 2014 18:35:01_

The signature of num.parse is given as:
  static num parse(String input, [Function num onError(String input)])
The "Function" should not be there. https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart-core.num#id_parse

_Original issue: http://code.google.com/p/dart/issues/detail?id=19283_

**Comment by sethladd** [comment]
This issue was moved to dart-lang/dartdoc#127
