### ISSUE TITLE
Generated dartdoc-viewer link hits page not found 

### ISSUE THREAD

**Issue by IssuesMigrator** [dart-lang/dartdoc-viewer#95]
_From [financeC...@gmail.com](https://code.google.com/u/104569492481999771226/) on June 09, 2014 18:57:38_

Not exactly sure why this happens. Viewing documentation for a class the right side of the page has a navigation view of the class. If you click on the first link, the actual class it will redirect to page not found. 

Example: http://www.dartdocs.org/documentation/stats/0.1.2/index.html#stats/fpsstats.Stats Click on the top right side where it says "Stats" will link to http://www.dartdocs.org/documentation/stats/0.1.2/stats/fpsstats.Stats My guess is the link should be http://www.dartdocs.org/documentation/stats/0.1.2/#stats/fpsstats.Stats

_Original issue: http://code.google.com/p/dart/issues/detail?id=19314_

**Comment by sethladd** [comment]
Thanks for the report. Future work is happening on https://github.com/dart-lang/dartdoc and we expect to address issues like this.
