### ISSUE TITLE
Api.dartlang.org shows the same subclass several times if exported.

### ISSUE THREAD

**Issue by IssuesMigrator** [dart-lang/dartdoc-viewer#98]
_From @lrhn on June 27, 2014 10:17:27_

The documentation of https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart-core.List shows:

Subclasses: UnmodifiableListView, UnmodifiableListView, UnmodifiableListView

This is actually the *same* class being re-exported by both package:collection/collection.dart and package:collection/wrappers.dart.

If possible, please detect when the same class is being referred to more than once, and only pick the most original declaration of it. The two other ways to reference the same class do not add anything useful here.

_Original issue: http://code.google.com/p/dart/issues/detail?id=19691_

**Comment by sethladd** [comment]
I see a single mention of UnmodifiableListView now.

**Comment by sethladd** [comment]
![screen shot 2015-01-16 at 12 40 47 pm](https://cloud.githubusercontent.com/assets/5479/5783984/ea7a683c-9d7c-11e4-8cb1-0a96fbbc8d28.png)
